server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**

        - id: bankaccount-service
          uri: lb://bankaccount-service
          predicates:
            - Path=/api/v1/bank_accounts/**

        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/v1/credits/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/v1/transactions/**

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/reports/**

        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/v1/cards/**

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/v1/wallets/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
